---
gem_packages:
  - { name: cocoapods }
  - { name: docker-sync }
  - { name: bundler }
  - { name: rbenv-rehash }
  - { name: pry }
  - { name: rubocop }
  - { name: travis }

pip_packages:
  - { name: chalice }
  - { name: powerline-status }
  - { name: psutil }
  - { name: netifaces }
  - { name: ansible }
  - { name: ansible_lint }
  - { name: ansible_shell }
  - { name: awslogs }
  - { name: jmespath-terminal }
  - { name: boto3 }
  - { name: doc2dash }
  - { name: sphinx }
  - { name: guzzle_sphinx_theme }

go_packages:

npm_packages:
  - { name: serverless }
  - { name: jsonlint }
  - { name: eslint }
  - { name: jslint }

