---
# - name: Change /usr/local owner to "{{ ansible_user_id }}"
#   become: true
#   become_method: sudo
#   file:
#     dest: /usr/local
#     owner: "{{ ansible_user_id }}"
#     group: admin
#     recurse: yes
# 
- name: Install homebrew
  shell: |
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: Add homebrew taps
  community.general.homebrew_tap:
    name: "{{ item.tap }}"
    state: present
  with_items:
    - "{{ homebrew_taps }}"

- name: Update homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: Install homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    install_options: 'appdir=/Applications'
  with_items:
    - "{{ homebrew_cask_packages }}"

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: "{{ item.state | default('latest') }}"
  with_items:
    - "{{ homebrew_packages }}"
