---
- name: Install Ruby via rbenv
  shell: |
    zsh -cl 'rbenv install "{{ ruby_version }}"'
  args:
    creates: "~/.anyenv/envs/rbenv/versions/{{ ruby_version }}/bin/ruby"

- name: Check if Ruby version is "{{ ruby_version }}"
  shell: |
    zsh -cl 'rbenv versions' | grep -F "* {{ ruby_version }}"
  register: res
  check_mode: no
  failed_when: no
  changed_when: res.rc != 0
  notify:
    - Change Ruby version

- name: Flush handlers
  meta: flush_handlers

- name: Install gem pacakges
  gem:
    name: "{{ item.name }}"
    user_install: no
    include_doc: yes
    state: "{{ item.state | default('latest') }}"
  with_items:
    - "{{ gem_packages }}"
